### PR TITLE
[WIP] Add fullscreen panel for album creation

### PR DESCRIPTION
**Pull request by GoOz**
- [x] Add "New Album" button in toolbar 
- [x] Add component of a fullscreen panel for album creation
- [x] Add panel's header & footer style
- [ ] Add Photoboard inside panel
- [ ] Submission

### CODE REVIEW

**Comment by enguerran** [comment]
I add some tasks:

- [ ] Add a event listener on the button "New Album"
- [ ] Display the panel when needed
- [ ] Cancel the "New Album" creation (and close the panel)

And a actual screenshot:
screenshot at 08-47-01

**Comment by GoOz** [comment]
[(3) [PHO-24] ETU je peux créer un nouvel album](https://trello.com/c/nnVGC9xn/270-3-pho-24-etu-je-peux-creer-un-nouvel-album)

**Comment by kosssi** [comment]
on fait quoi de cette PR @GoOz ?

**Comment by GoOz** [comment]
Rien. :)

**Pull request closed without merging**
