### PR TITLE
[refacto] Fix typo in PhotosList component name

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Comment by gregorylegarec** [comment]
@y-lohse Yep, pretty weird actually. But everything seems ok on my machine. The branch on my repo is OK too. https://github.com/gregorylegarec/cozy-photos-v3/tree/refacto/rename-photoslist/test/components
I think (hope?) we can trust them.

**Comment by y-lohse** [comment]
Ok, merging it, and we can add the missing files later if they turn out to be really missing!

**Comment by gregorylegarec** [comment]
@y-lohse It seems they're here 👍 

https://github.com/cozy/cozy-photos-v3/blob/master/test/components/photoList.spec.jsx

**Comment by y-lohse** [comment]
That is so weird. But glad it's all good :)

**Pull request merged**
