### PR TITLE
feat: better album modal paddings :lipstick:

### PR DESCRIPTION
**Pull request by gregorylegarec**
capture d ecran 2017-06-02 a 17 29 39

### CODE REVIEW

**Comment by gregorylegarec** [comment]
I don't mind, but don't forget those changes https://github.com/cozy/cozy-photos-v3/pull/97/files#diff-98699a455d0771d8a685b627e000c6f0 :)

**Comment by GoOz** [comment]
This modal is just madness from my perspective. I really need to clean this up. I'm not sure but i have a scheduled pairing session with our beloved designer, maybe this is something i'll do.

**Comment by gregorylegarec** [comment]
Out of date and not needed anymore.

**Pull request closed without merging**
