### PR TITLE
[WIP] feat: Add Share button + share modal

### PR DESCRIPTION
**Pull request by GoOz**
Here are the share button and the modal.
Without functionality, just HTML/CSS

### CODE REVIEW

**Comment by enguerran** [comment]
@GoOz I will fetch it to my local repository and push my changes on this PR.

**Comment by GoOz** [comment]
Wait! something's broken :/

**Comment by GoOz** [comment]
False alarm. My watcher was fooling around. But Travis doesn't seem to like either. :/

**Comment by enguerran** [comment]
Replaced by #74

**Comment by enguerran** [comment]
[(2) [PHO-28 Partage d'un album par lien] Générer un lien de partage](https://trello.com/c/QFFEMBdU/280-2-pho-28-partage-d-un-album-par-lien-generer-un-lien-de-partage)

**Pull request closed without merging**
