### PR TITLE
Enable local stack assets dev mode

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by m4dz** [comment]
It seems that https://github.com/m4dz/cozy-photos-v3/blob/chore/stack-assets/src/actions/mango.js#L21 has an issue, but I can't figure why:

```txt
Unhandled promise rejection TypeError: NetworkError when attempting to fetch resource.
Stack trace:
isV2/this._version<@http://app.cozy.local:8080/app.js:1111:17
doTry@http://app.cozy.local:8080/app.js:1220:14
doTry/</<@http://app.cozy.local:8080/app.js:1225:16
run@http://app.cozy.local:8080/app.js:36148:23
notify/<@http://app.cozy.local:8080/app.js:36161:29
flush@http://app.cozy.local:8080/app.js:36463:10
MutationCallback*module.exports@http://app.cozy.local:8080/app.js:36482:6
@http://app.cozy.local:8080/app.js:36074:27
__webpack_require__@http://app.cozy.local:8080/app.js:20:12
@http://app.cozy.local:8080/app.js:103:2
@http://app.cozy.local:8080/app.js:47:30
__webpack_require__@http://app.cozy.local:8080/app.js:20:12
@http://app.cozy.local:8080/app.js:40:18
@http://app.cozy.local:8080/app.js:1:11
```

@CPatchane, any idea?

**Comment by m4dz** [comment]
Oh! Fine, tests fail because of lack of global `cozy` module, I'm finding a working, hang on :)

**Comment by m4dz** [comment]
Tests are now ok, but I still have a `fetch` error, due to a CSP rule:

```txt
Content Security Policy: The page’s settings blocked the loading of a resource at http://undefined/status/ (“default-src http://app.cozy.local:8080 http://cozy.local:8080”).
```

Did anybody knows how we are requesting `http://undefined/status/` oO?!

**Comment by m4dz** [comment]
Everthings is now on green \o/ ! Ready to merge :rocket:

**Comment by gregorylegarec** [comment]
Thanks @m4dz !

**Pull request merged**
