### PR TITLE
feat: remove from album :heavy_minus_sign:

### PR DESCRIPTION
**Pull request by enguerran**
I have two problems with this feature:

1. I added some context in `SelectionBar`: router (to get the location), and the current album. Do you think it is a good solution?
1. */unresolved/* How can I refresh the `AlbumPhotos` component as it is not connected to the redux store (in fact, album's photos are fetched in the component, not in the global state)

Don't hesitate to give an opinion or to send some good tricks!

### CODE REVIEW

**Comment by gregorylegarec** [comment]
@enguerran Maybe it's time to locate Albums in the redux store ?

**Comment by goldoraf** [comment]
@gregorylegarec: they're, in a duck ;)

**Comment by enguerran** [comment]
Okay, so I let this code as this.
To see the new content of the album, you need to refresh the page.

And we'll do a refactoring to manage albums and photos state within the global redux state, so a `push` or `slice` will refresh the needed component. Are we ok?

**Comment by enguerran** [comment]
[(2) [PHO-20] ETU je peux retirer une photo d'un album existant DBD réorganiser cet album](https://trello.com/c/ulFpGjU1/246-2-pho-20-etu-je-peux-retirer-une-photo-d-un-album-existant-dbd-reorganiser-cet-album)

**Pull request merged**
