### PR TITLE
feat: add cozy-bar in public/

### PR DESCRIPTION
**Pull request by enguerran**
This PR customizes the `public/index.html` to accept JavaScript and a preact aoo.
And it let the cozy.bar be initialized.

I'm still waiting for tips to init the cozy-bar without everything a `public/` path do not need (settings menu, app menu, etc.). If someone has some, please, be my guest.

screenshot at 16-43-58

### CODE REVIEW

**Comment by enguerran** [comment]
[(1) [PHO-27 Partage d'un album par lien] Création d'une page publique simple](https://trello.com/c/gwhjazOi/279-1-pho-27-partage-d-un-album-par-lien-creation-d-une-page-publique-simple)

**Comment by m4dz** [comment]
I've added a `public` mode for the Bar in https://github.com/cozy/cozy-bar/pull/47 :wink:

**Comment by enguerran** [comment]
I updated the PR to use the new version of `cozy-bar`. It is ready to go!

kehmuvo

**Comment by enguerran** [comment]
@m4dz Have you a clue to load the icon image with no permission?

**Pull request merged**
